### PR TITLE
React version of demo

### PR DESCRIPTION
**Pull request by joelvh**
This is a port to React.

* [x] Render HTML layout in React
* [x] Port all blocks to React components
* [x] Port event listeners to React lifecycle
* [x] Create adapter from React to Flowy engine
* [x] Implement minimizing left card
* [x] Improve highlighting blocks and toggle right card

This builds on the work in #37 and #38

### CODE REVIEW

**Comment by joelvh** [comment]
@alyssaxuu the React implementation of the demo is done. This focused on getting the current demo working as a React version, with some bug fixes and the ability to minimize the left card.

I will continue refactoring flowy and the React implementation in another branch to implement new features and fix some buggy flowy behavior when clicking blocks.

Any feedback to get this merged?

**Comment by alyssaxuu** [comment]
Nice! Just wondering how that would merge though - I do want to have a non-React version, so would it be in a different branch/folder? Also there's been some bug fixes/enhancements since you made these commits.

**Comment by joelvh** [comment]
@alyssaxuu the goal here was to keep the non-React version in-tact, separating it from the React-based version. In terms of merging things, we'd look at the new commits and port those updates to this branch. As mentioned in #37, we can also keep the build artifacts in the git repository as working demo code for simplicity of showcasing the output (for React- and non-React-based versions). If you get a chance to checkout this branch, you'll see locally, it's organized as separate sets of code -- again, focusing on keeping the non-React as-is and the React version builds on top of that as an example of how to use it with React.

**Comment by vinayakkulkarni** [comment]
damn! I have vue version lying around in my repo..

**Comment by AllanOricil** [comment]
> damn! I have vue version lying around in my repo..
> 
> but yeah, keeping flowy framework free would be the best thing
Could you share your vue implementation?

**Comment by joshbedo** [comment]
I'd love to use this if it's still a thing :)

**Comment by joshbedo** [comment]
Any way i can pull this in as a module or something for my project? @joelvh

**Comment by joelvh** [comment]
@joshbedo the demo worked when I created the PR - however, I had started refactoring flowy to use ES6 and @alyssaxuu has decided not to go that direction, nor with NPM. I'm afraid this is a bit outdated now (in terms of having the latest from `master`). I may come back to this in the future, but unsure as to how flowy will be managed going forward.

**Comment by vinayakkulkarni** [comment]
It's MIT Licensed! You can always fork and create your own ES6, Vue, Svelte, Angular, Alpine or even React version of it.

Super glad that @alyssaxuu has kept the philosophy as per her understanding and not being forced of making this into a framework specific plugin/pkg.

**Comment by joelvh** [comment]
@vinayakkulkarni yep - that's absolutely right. Will revisit when I have time.

**Comment by joshbedo** [comment]
@joelvh did you happen to see this error at all when running the React version? Can't seem to get the `snapping` function to execute properly it keeps erroring out with `drag.querySelector` is undefined. Not too sure what could be causing this. I've been digging through the source code all day.

Screen Shot 2020-05-03 at 6 36 59 PM

**Comment by joshbedo** [comment]
Another screenshot, seems really odd.
Screen Shot 2020-05-03 at 6 47 58 PM

**Comment by joelvh** [comment]
@joshbedo are you getting those errors when you run `npm run react` in the root of my branch? That should launch the React demo.

**Comment by joshbedo** [comment]
I was using the react branch you created and ran npm start i believe. I ended up just recreating the vanilla version in React and got it working. Looking through all your code helped a lot though!

**Comment by VINCIDAO** [comment]
Hello

Also trying to import this to react. Any way I can get it?

**Pull request closed without merging**
